project:
  type: website

resources:
  - CNAME
website:
  title: "Nathan Cashion"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nathancashion/
      - icon: twitter
        href: https://x.com/nathancashion
      - icon: linkedin
        href: https://www.linkedin.com/in/nathancashion/
format:
  html:
    respect-user-color-scheme: true
    theme: litera
    css: styles.css
site-url: https://quarto.nathancashion.com
description: "Nathan Cashion's personal website and blog powered by Quarto."
repo-url: https://github.com/nathancashion/Quarto_blog


editor: visual

