project:
  type: website

website:
  title: "Nathan Cashion"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    respect-user-color-scheme: true
    theme: litera
    css: styles.css
siteurl: https://nathancashiongithub.io/Quarto_blog
repourl: https://github.com/nathancashion/Quarto_blog


editor: visual

